SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Corrections](
	[CorrectionDescription] [nvarchar](max) NOT NULL,
	[EscapeCause] [nvarchar](max) NOT NULL,
	[Action] [nvarchar](max) NOT NULL,
	[ConformityId] [int] IDENTITY(1,1) NOT NULL,
	[CPARId] [int] NOT NULL,
UNIQUE NONCLUSTERED 
(
	[CPARId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
